import pytest
from plesk_unified.server import (
    mcp,
    plesk_extension_dev_guide,
    plesk_api_integration,
    plesk_cli_reference,
)


@pytest.mark.asyncio
async def test_prompts_are_registered():
    """Verify that the expected prompts are registered in the MCP instance."""
    prompts = await mcp.list_prompts()
    registered_prompt_names = {p.name for p in prompts}
    expected_prompts = {
        "plesk-extension-dev-guide",
        "plesk-api-integration",
        "plesk-cli-reference",
    }
    assert expected_prompts.issubset(registered_prompt_names)


def test_plesk_extension_dev_guide_content():
    """Test the content generated by plesk-extension-dev-guide."""
    extension_name = "MyAwesomeExtension"
    target_language = "Python"
    content = plesk_extension_dev_guide(extension_name, target_language)
    assert len(content) > 0
    assert extension_name in content
    assert target_language in content


def test_plesk_api_integration_content():
    """Test the content generated by plesk-api-integration."""
    api_operation = "customer.get"
    content = plesk_api_integration(api_operation)
    assert len(content) > 0
    assert api_operation in content


def test_plesk_cli_reference_content():
    """Test the content generated by plesk-cli-reference."""
    command_name = "domain"
    content = plesk_cli_reference(command_name)
    assert len(content) > 0
    assert command_name in content
