import pytest
from unittest.mock import MagicMock
from plesk_unified.server.mcp_app import create_mcp_app
from plesk_unified.application.services.container import AppContainer


@pytest.fixture
def mock_app_container():
    # We mock everything needed for AppContainer
    return MagicMock(spec=AppContainer)


@pytest.fixture
def mcp_app(mock_app_container):
    return create_mcp_app(mock_app_container)


@pytest.mark.asyncio
async def test_prompts_are_registered(mcp_app):
    """Verify that the expected prompts are registered in the FastMCP instance."""
    prompts = await mcp_app.list_prompts()
    for p in prompts:
        print(f"Registered prompt: {p.name}, args: {p.arguments}")
    registered_prompt_names = {p.name for p in prompts}

    expected_prompts = {
        "plesk-extension-dev-guide",
        "plesk-api-integration",
        "plesk-cli-reference",
    }
    assert expected_prompts.issubset(registered_prompt_names)


@pytest.mark.asyncio
async def test_plesk_extension_dev_guide_content(mcp_app):
    """Test the content generated by plesk-extension-dev-guide."""
    extension_name = "MyAwesomeExtension"
    target_language = "Python"

    # FastMCP.render_prompt returns a PromptResult object
    result = await mcp_app.render_prompt(
        "plesk-extension-dev-guide",
        arguments={
            "extension_name": extension_name,
            "target_language": target_language,
        },
    )

    content = result.messages[0].content.text
    assert extension_name in content
    assert target_language in content


@pytest.mark.asyncio
async def test_plesk_api_integration_content(mcp_app):
    """Test the content generated by plesk-api-integration."""
    api_operation = "customer.get"
    result = await mcp_app.render_prompt(
        "plesk-api-integration", arguments={"api_operation": api_operation}
    )

    content = result.messages[0].content.text
    assert api_operation in content


@pytest.mark.asyncio
async def test_plesk_cli_reference_content(mcp_app):
    """Test the content generated by plesk-cli-reference."""
    command_name = "domain"
    result = await mcp_app.render_prompt(
        "plesk-cli-reference", arguments={"command_name": command_name}
    )

    content = result.messages[0].content.text
    assert command_name in content
